// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXDyvAmo-nP89awachQ8w8Vc_LYj9qZXs',
    appId: '1:126486177996:web:110ed01f5cb6cfc63bfa69',
    messagingSenderId: '126486177996',
    projectId: 'quraa-otp',
    authDomain: 'quraa-otp.firebaseapp.com',
    storageBucket: 'quraa-otp.firebasestorage.app',
    measurementId: 'G-9Q32QJ6E2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2BWS786GSZKZc8PiZrfV05piXXnxwrE',
    appId: '1:126486177996:android:6e7a7fe20bcb49fc3bfa69',
    messagingSenderId: '126486177996',
    projectId: 'quraa-otp',
    storageBucket: 'quraa-otp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRdtwawgxIcH3mP2qZAQ6H1DE6sMlGU2E',
    appId: '1:126486177996:ios:b602c6add6455da23bfa69',
    messagingSenderId: '126486177996',
    projectId: 'quraa-otp',
    storageBucket: 'quraa-otp.firebasestorage.app',
    iosBundleId: 'com.example.quraaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRdtwawgxIcH3mP2qZAQ6H1DE6sMlGU2E',
    appId: '1:126486177996:ios:b602c6add6455da23bfa69',
    messagingSenderId: '126486177996',
    projectId: 'quraa-otp',
    storageBucket: 'quraa-otp.firebasestorage.app',
    iosBundleId: 'com.example.quraaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXDyvAmo-nP89awachQ8w8Vc_LYj9qZXs',
    appId: '1:126486177996:web:138d21dcaf9175603bfa69',
    messagingSenderId: '126486177996',
    projectId: 'quraa-otp',
    authDomain: 'quraa-otp.firebaseapp.com',
    storageBucket: 'quraa-otp.firebasestorage.app',
    measurementId: 'G-BY4F4DWVEV',
  );
}
